language: python
python:
  - "2.7.15"
  - "3.6"
  - "3.7"
dist: xenial
sudo: required
services:
  - docker
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
  - PLONE_VERSION=5.1.x
  - PLONE_VERSION=5.2.x
  global:
    - secure: "tj9kO7Uyn7AY2Z6zhdOggLSYheaD8e+qKA7ZXvdWTrL2HtPAtnNJK8keQGj1JLQyy6bRfoOCt51aL8+Lc0fzcACaLFpAPjleSLtUChphPOh/dqTu1QX5oL0SxZ94B4ZC5+qfaSAQHMwbiiWUW0us9QtJpxQQmiJUekqiTdQDNEo="
    - secure: "j06un+j2gHjlGfg+xMcvKG2osf1HSzBq/cPPNIonnjGQY3GJfT/YRzYnHe5LJPPt7IJDD7hAEPentRJ4C0zP66U6gcQ2HjWPsMIcvzlgnXoT2QaaCVkMA9YS4WOsN0C5iY/R64GjFwR7J+/bgeG64XvfhpuQ/UBP2+U68PqSBtM="
matrix:
  exclude:
    - python: 3.6
      env: PLONE_VERSION=4.3.x
    - python: 3.6
      env: PLONE_VERSION=5.0.x
    - python: 3.6
      env: PLONE_VERSION=5.1.x
    - python: 3.7
      env: PLONE_VERSION=4.3.x
    - python: 3.7
      env: PLONE_VERSION=5.0.x
    - python: 3.7
      env: PLONE_VERSION=5.1.x
  allow_failures:
  - python: "3.6"
    env: PLONE_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -t 10 -c travis.cfg
script:
  - bin/code-analysis
  - bin/sphinxbuilder
  - bin/test
  - bin/test-no-uncommitted-doc-changes
  - bin/test-no-sphinx-warnings
after_success:
  - bin/test-coverage
  - pip install coverage==3.7.1 coveralls
  - coveralls
